# Generated by Django 4.2.7 on 2023-12-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='buyer_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
