# Generated by Django 4.2.7 on 2023-12-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(default=0)),
                ('writter_id', models.IntegerField(default=0)),
                ('writter_name', models.CharField(max_length=200)),
                ('comment', models.TextField(null=True)),
            ],
        ),
    ]
