# Generated by Django 4.2.7 on 2023-12-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('full_name', models.CharField(max_length=200)),
                ('birth', models.IntegerField(default=0)),
                ('address', models.CharField(max_length=200)),
                ('post', models.CharField(max_length=200)),
                ('tel', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=200)),
                ('is_authenticated', models.BooleanField(default=False)),
            ],
        ),
    ]
