# Generated by Django 4.2.7 on 2023-12-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_authenticated',
        ),
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
